# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - unconvert
    - unparam
  
  exclusions:
    paths:
      - internal/mock
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - dupl
  
  settings:
    revive:
      rules:
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf

formatters:
  enable:
    - gofmt
    - goimports
  
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/kdimtriCP/gh-inspector